### ISSUE TITLE
Create better design

### ISSUE THREAD

**Issue by zhoraygevorgyan** [epicbg/epic-ui#21]
![image](https://user-images.githubusercontent.com/53972372/67143036-d6c46e80-f26f-11e9-9e53-6aac71d894b6.png)
You cannot tell that dropdown is not part of the menu, fix that and put design here

**Comment by nedzone** [comment]
Hello dear. @jesuskostov 
Can you please code this Sidebar 
![image](https://user-images.githubusercontent.com/14924529/67145257-9c1b0000-f288-11e9-8cf3-8df76cd58fd2.png)


[Copy of NAV bar.zip](https://github.com/epicbg/epic-ui/files/3746676/Copy.of.NAV.bar.zip)
Thank you very much!

**Comment by zhoraygevorgyan** [comment]
I already coded this @jesuskostov . Skip this
