### ISSUE TITLE
Introduction page of docs

### ISSUE THREAD

**Issue by zhoraygevorgyan** [epicbg/epic-ui#22]
I need 3 skeleton images for docs introduction page.
1 for gettings started, 2 for snippet, 3 for templates. 
![image](https://user-images.githubusercontent.com/53972372/67143773-8224f180-f277-11e9-8c94-bf8a40451f4e.png)

This is what skeleton looks like
![image](https://user-images.githubusercontent.com/53972372/67143796-d334e580-f277-11e9-80e4-3b691425c943.png)

1st should look like .txt file's icon, 2nd should be similar to the snippet I sent and 3rd should look like website wireframe similar to 2nd's design.

**Comment by nedzone** [comment]
Task is done
[Skeleton IMG.zip](https://github.com/epicbg/epic-ui/files/3746756/Skeleton.IMG.zip)
