### ISSUE TITLE
Create flexbox grid

### ISSUE THREAD

**Issue by zhoraygevorgyan** [epicbg/epic-ui#6]
Create dynamic flexbox grid system with predefined sizes from xs through xl. Create container class, row class. Define breakpoints of the system.
this is demo example how it should work

````html
        <div class="row">
            <div class="col sm-2"></div>
            <div class="col sm-3"></div>
            <div class="col"></div>
        </div>
````
.col's should adjust their width themselfs until they get assigned breakpoint size (e.g. md-2)

**Comment by zhoraygevorgyan** [comment]
This issue and our grid system is frozen because it stops the workflow. at the moment we're using flexboxgrid.com's grid system until we have our own FULLY FUNCTIONAL grid system

**Comment by cbsorrilha** [comment]
Hey, can I help you?
What's the specs to this grid? You want something strictly similar in function to the flexboxgrid.com grid system or can you think about other features?

**Comment by zhoraygevorgyan** [comment]
Hey, thank you for asking.
Yes I want similar to their grid system except two things. 

- I want to make classes shorter, for example md-5, sm-3 etc..
- I want to create equal column sizes using only 1 column class e.g:
```html
<div class="row">
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
</div>
```
this will create 3 columns:  4---- 4 ---- 4 ----
And then adjust the sizes with any class for breakpoint e.g.:
```html
<div class="row">
     <div class="col sm-2"></div>
     <div class="col sm-3"></div>
     <div class="col"></div>
</div>
```
and the grid will look like this: 2-- 3--- 7------


I saw the issue for contributing.md I am working on it.

**Comment by cbsorrilha** [comment]
Nice, I'll make a pull request on it.
