### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by cbsorrilha** [epicbg/epic-ui#9]
**Is your feature request related to a problem? Please describe.**
Me as a new contributor want to begin contributing to the project and don't know exactly where to start.

**Describe the solution you'd like**
A CONTRIBUTING.md file with instructions on where to begin and what rules to follow when commiting and opening a pull request;

**Comment by zhoraygevorgyan** [comment]
Thanks for the issue. I'm working on it. I'll also add slack, make sure you join :)

**Comment by cbsorrilha** [comment]
I can't join the slack. :(
It keeps asking me to get a invite.

**Comment by zhoraygevorgyan** [comment]
Here, this is temporary link https://join.slack.com/t/epic-uiworkspace/shared_invite/enQtNzcwODA1MDk5NDk0LTA2ZGYwZWM0YjUyZThmN2VhYjk4OWEzNDg3NGZjMzc4NmZhNDVlM2E1NzNhYWYxOTFlZTAyNGQ2N2ZlYWNmNmQ
